### PR TITLE
Add support for UNMAPPED and taxon identifiers

### PR DESCRIPTION
**Pull request by jraysajulga**

### CODE REVIEW

**Comment by bebatut** [comment]
Thanks a lot @jraysajulga 
Just a quick question. Could you update the test data?
The command is

```
/group_humann2_uniref_abundances_to_GO.sh -i "test-data/humann2_gene_families.csv" -a "test-data/go_02_22_2016.obo" -s "test-data/goslim_metagenomics_02_22_2016.obo" -u "test-data/map_infogo1000_uniref50_02_22_2016.txt" -g `which map_to_slim.py | xargs -n1 dirname` -p `which humann2 | xargs -n1 dirname` -m "test-data/molecular_function_abundances.txt" -b "test-data/biological_process_abundance.txt" -c "test-data/cellular_component_abundance.txt"
```

Thanks 😄

**Comment by jraysajulga** [comment]
No problem. Thanks for taking a look, @bebatut.

I have updated the test data.

**Comment by bebatut** [comment]
Thanks a lot @jraysajulga

**Comment by bebatut** [comment]
I will create a release to be able to update the bioconda package

**Pull request merged**
