### PR TITLE
Update format_humann2_output.py

### PR DESCRIPTION
**Pull request by cbulow**
Thank you for this very useful function! I have been using it to trim down some humann2 data involving comparisons between samples. For input I have a merged and normalized table humann2 output. I've made some changes to format_humann2_output.py to accept this file type as input and thought others might find them useful.

This branch supports humann2 multi-sample merged tables as input and writes a column for each sample abundance in the output files. Additionally, this branch supports input files that contain additional information after the "UNGROUPED" designation or are labeled "UNMAPPED". I have attached a test input table.

Cheers!
Chris

More info on humann2 multi-sample merged tables: https://bitbucket.org/biobakery/biobakery/wiki/humann2#rst-header-humann2-for-multiple-samples

### CODE REVIEW

**Comment by bebatut** [comment]
Hi,

Thanks for your contribution.
It looks nice.

The [test checks](https://travis-ci.org/ASaiM/group_humann2_uniref_abundances_to_GO/builds/160057613) are failing because of column header changes.
Could you update the `test-data` to follow your changes, please? 
Even better, could you add new test data to test your new functionality?
Thanks a lot,

Bérénice

**Comment by cbulow** [comment]
Hello,

I have created a pull request for merging this script (#5) that has an updated multisample multisample test script and output files. I'm still working on rounding and spacing compatibility. 

Thanks,
Chris

**Comment by bebatut** [comment]
@cbulow Why did you close this PR? Sorry for the delay, but I planned to check and work on this tomorrow first hour... I can still add the functionality. Thanks for you contribution

**Comment by cbulow** [comment]
I'm making a few edits and I will submit a cleaner pull request shortly. There were a few inconsistencies in rounding abundance values.

**Comment by bebatut** [comment]
👍 
Thanks

**Comment by cbulow** [comment]
I've fixed the rounding issue by rounding to the nearest integer and modified the test file to accept the multi-file header(#7). Let me know how this looks!

**Pull request closed without merging**
